# This workflow will generate a release distribution and upload it to PyPI

name: Publish Build and GitHub Release
on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_publish_docker:
    needs: build_and_publish_pypi_and_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@FIX_DockerNullTagChecks
    secrets: inherit
    with:
      image_name: test_bus_automation