# This workflow will generate a release distribution and upload it to PyPI

name: Test Docker
on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_publish_docker:
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@FIX_DockerNullTagChecks
    secrets: inherit
    with:
      image_name: neongeckocom/test_bus_automation