# This workflow will run unit tests

name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install portaudio19-dev python3-pyaudio
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt

      - name: Test Utilities
        run: |
          pytest tests/test_utils.py --doctest-modules --junitxml=tests/util-test-results.xml
      - name: Upload Util test results
        uses: actions/upload-artifact@v2
        with:
          name: util-test-results
          path: tests/util-test-results.xml

      - name: Test Service
        run: |
          pytest tests/test_messagebus_service.py --doctest-modules --junitxml=tests/messagebus-service-test-results.xml
      - name: Upload Messagebus service test results
        uses: actions/upload-artifact@v2
        with:
          name: messagebus-service-test-results
          path: tests/messagebus-service-test-results.xml
